<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>67fd0646-39ab-4a73-b3d2-29cabfcea9ba</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.4" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\deploy-or-die-backend\DeployOrDie.Api\DeployOrDie.Api.csproj" />
  </ItemGroup>

</Project>
